# Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.10
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_id=doorman
mod_name=Esoteria
mod_description=Odin addon pack created by Lana.
mod_version=1.3.2
maven_group=com.odtheking
archives_base_name=esoteria

# Mod Dependencies
fabric_kotlin_version=1.13.10+kotlin.2.3.20
fabric_api_version=0.138.4+1.21.10
devauth_version=1.2.2
commodore_version=1.0.1

# Other Properties
kotlin_version=2.3.20
kotlin.code.style=official
minecraft_lwjgl_version=3.3.3

# Supports release versions or commit hashes.
odin_version=0.1.9
